language: go
dist: trusty
sudo: false
go:
  - 1.6
addons:
  apt_packages:
    - libgl1-mesa-dev
    - xorg-dev
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
script:
  - go get github.com/furushchev/phys-anime
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - if [ "$TRAVIS_TAG" != "" ]; then ghr -u furushchev -t $GITHUB_TOKEN -p 4 --replace --prerelease --delete --prerelease $TRAVIS_TAG dist/; fi
